### ISSUE TITLE
support for Python>3.10

### ISSUE THREAD

**Issue by qyx268** [qyx268/astrodatapy#20]
it seems that the packages only works with Python <=3.10 due to the patch infrastructure used by the astropy packaging stuff. 

Edited 25/Nov/2024:

Apparently,  astropy 6.1.4 doesn't do 'update_default_config' from 'astropy.config.configuration', also need to update

there seems to also be a bug of astropy.registers for astropy>5.3

**Comment by EMventura** [comment]
So does this work for Python 3.10 for you?

**Comment by qyx268** [comment]
yeah, it doesn't for you? 
![image](https://github.com/user-attachments/assets/b4e9669c-ab25-4546-9c62-a0f32ebc2c85)

**Comment by EMventura** [comment]
Maybe there is some conflict, I get this error when I try to import number_density:

cannot import name 'update_default_config' from 'astropy.config.configuration' (/fred/oz113/eventura/miniconda3/envs/DraSector2/lib/python3.10/site-packages/astropy/config/configuration.py

I'll figure it out

**Comment by qyx268** [comment]
what's your astropy's version? Mine is 5.2.2

**Comment by EMventura** [comment]
5.1, I'll try to install 5.2.2

**Comment by EMventura** [comment]
Actually I had astropy 6.1.4 which indeed aborted the function update_default_config from 'astropy.config.configuration now I changed to 5.3.4 and it works

**Comment by qyx268** [comment]
there seems to also be a bug of `astropy.registers` for astropy>5.3

**Comment by manodeep** [comment]
@qyx268 Hmmm if you have a reproducer, then you should open an issue on the Astropy repo

**Comment by qyx268** [comment]
@manodeep they are just gonna tell you to update... i'll find a time to update this...

**Comment by manodeep** [comment]
Not sure I follow - I thought that you said that the later versions have the bug (perhaps in combination with python version?)
